//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanatorium.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procedur
    {
        public int ProcedureId { get; set; }
        public string ProcedureName { get; set; }
        public System.DateTime ProcedureDate { get; set; }
        public int PatientId { get; set; }
        public int DoctorId { get; set; }
        public int CabinetNumber { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
